### ISSUE TITLE
Genres are undefined

### ISSUE THREAD

**Issue by danielgrijalva** [danielgrijalva/overworld#22]
**Describe the bug**
The genres array is undefined for the game `Puyo Puyo Tetris`, but this bug probably happens in other games too.

**To Reproduce**
1. Search for "Puyo Puyo Tetris"
2. Go to its game details page
3. Click on the "Genres" tab

**Expected behavior**
You should see the genres of the game (`Puzzle` in this case)

**Screenshots**
![image](https://user-images.githubusercontent.com/11547406/57237370-e9a5f800-6fdb-11e9-93ba-ad0a053ebfab.png)

**Additional context**
The genres *are* there. Printing to console at mounting works.

**Comment by NeutralDread** [comment]
Hello, I would like to take this issue. I rand through the contributions steps but am having issues getting the backend up. When i run  `python manage.py migrate`
```
I'm getting:
  from django.urls import path, include
ImportError: cannot import name path

**Comment by danielgrijalva** [comment]
Hi! which Python version are you using? and what OS?

**Comment by danielgrijalva** [comment]
The `path` module is from Django 2.0+, which only works with Python 3.4+, so chances are you are running it with Python 2 :thinking: 

https://stackoverflow.com/a/48524457

**Comment by NeutralDread** [comment]
Thanks for the fast reply!
I'm using Mac OS Sierra 10.12.6
and have python3 installed but even when i run python3 manage.py migrate i get the same result

**Comment by NeutralDread** [comment]
I followed the steps in the link you provided and got it running. Thank you! 
Going to look into this issue

**Comment by danielgrijalva** [comment]
Oh damn, it appears this issue is no longer relevant... we migrated to the IGDB API recently and the error doesn't happen anymore, at least on my end :thinking: can you please confirm this, @NeutralDread?

**Comment by NeutralDread** [comment]
@danielgrijalva was just gonna message you haha.
It looks like it was resolved

**Comment by NeutralDread** [comment]
Im seeing the genres populate correctly and no extra errors in console

**Comment by danielgrijalva** [comment]
Yeah sorry about that, I should've close the issue :sweat_smile: 

Glad you got the project to run though. If you want, you can take on issue #14 or #25. I'll be adding more documentation, issues and guidelines this coming days so stick around! :smile:

**Comment by NeutralDread** [comment]
No worries 😆
Thanks for the help, and I will check out any other issues i think i could contribute to and keep a look out for future ones!
